name: deploy1
on:
  push:
  pull_request:
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' #install the python version needed
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
          python-version: '3.9'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}